#[allow(dead_code)]
pub enum GameMode {
    FFA = 0,
    CoopEdit,
    TeamPlay,
    InstaGib,
    InstaGibTeam,
    Efficiency,
    EfficiencyTeam,
    Tactics,
    TacticsTeam,
    Capture,
    RegenCapture,
    CTF,
    InstaCtf,
    EfficiencyCtf,
    Protect,
    InstaProtect,
    EfficiencyProtect,
    Hold,
    InstaHold,
    EfficiencyHold,
    Collect,
    InstaCollect,
    EfficiencyCollect,
}